### PR TITLE
Add 'clippo' and 'kalk'

### PR DESCRIPTION
**Pull request by monsterkodi**
Neat package manager. I like it.

The `appget create`  command failed for me to upload the changes:

> Submit manifest to be reviewed and added to official repository?: yes
> Couldn't submit manifest HTTP Request to https://api.appget.net/packages failed. 405:MethodNotAllowed

But I guess a PR will do the same?

### CODE REVIEW

**Comment by monsterkodi** [comment]
Hi, yes I did use the appget create. It just didn't upload the yaml.

Anyways, what is the icon repository used for? Should I submit icons as well?

Thanks for your fast reply.

**Comment by kayone** [comment]
I'm working on a web gallery to display/search available packages, the icon will be used there, feel free to add icons for your apps there :)

**Comment by monsterkodi** [comment]
Cool, sounds good. Will add the icons then.

**Comment by kayone** [comment]
hey, I just found a bug in one of my automation scripts (your PR was the first external PR). anyways the bug caused your changes to be reverted. could you do another PR? I could just commit the changes my self, but I want you to remain the author of the commit.

**Comment by monsterkodi** [comment]
Yes, I will try.

**Pull request merged**
