### PR TITLE
Add Far Manager package

### PR DESCRIPTION
**Pull request by ekot1**

### CODE REVIEW

**Comment by kayone** [comment]
Thank you for your contribution :)

**Comment by kayone** [comment]
p.s, when adding github packages using the link from the releases section https://github.com/FarGroup/FarManager/releases is preffered. 

this should automatically get updated our github crawler runs in an hour or so.

**Comment by kayone** [comment]
as predicted, https://github.com/appget/appget.packages/pull/2904/files

**Comment by ekot1** [comment]
I think on github they have Nightly builds, rather than Stable builds. They distinguish it on download page https://www.farmanager.com/download.php?l=en

**Comment by kayone** [comment]
hmm, they don't flag their releases correctly. I'll open an issue in their repo and see if they can fix it.

**Pull request merged**
